import type { Metadata } from "next";
import AuthProvider from "@/provider/auth-provider";
import Navbar from "@/views/components/navbar";
import Footer from "@/views/components/footer";
import localFont from "next/font/local";
import "./globals.css";

// Font configurations
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {/* Flex container for sticky footer */}
          <div className="flex flex-col min-h-screen">
            <Navbar />
            {/* Main content with spacing at the bottom */}
            <main className="flex-grow mb-8">{children}</main>
            <Footer />
          </div>
        </body>
      </AuthProvider>
    </html>
  );
}
